const English = {
  homepage: "Homepage",
  searchAfroboost: "Search Afroboost",
  "Latest posts": "Latest posts",
  Everything: "Everything",
  Entertainment: "Entertainment",
  Sport: "Sport",
  Music: "Music",
  Film: "Film",
  Services: "Services",
  Podcasts: "Podcasts",
  Animations: "Animations",
  Tutorials: "Tutorials",
  Vouchers: "Vouchers",
  searchAuthor: "Search author on Afroboost",
  library: "Library",
  liked: "Liked",
  transfer: "Transfer",
  logout: "Logout",
  posts: "Posts",
  searchPostsAuthor: "Search author's posts",
  "Oldest posts": "Oldest posts",
  posted: "Posted",
  changeYourUsername: "Change your username",
  changeYourUsernameText:
    "Your name should consist only of alphanumeric characters and cannot contain any other characters.",
  yourNewUsername: "Your new username",
  cancel: "Cancel",
  profile: "Profile",
  boost: "Boost",
  message: "Message",
  autoplay: "Autoplay",
  confirm: "Confirm",
  changeYourBiography: "Change your biography",
  changeYourBiographyText:
    "Your biography will be publicly visible on your profile page.",
  yourNewBiography: "Your new biography",
  changeYourName: "Change your name",
  changeYourNameText:
    "Your name should consist only of alphabetic characters and cannot contain any other characters.",
  yourNewName: "Your new name",
  publishPost: "Publish a new post",
  publishPostFirst:
    "Share your content on Afroboost and earn money from sales. Paid videos and audio files will have a non-paid preview version.",
  titlePost: "Title for your post",
  descriptionPost: "Description for your post",
  pricePost: "Price for your post in CHF",
  upload: "UPLOAD",
  category: "Category",
  noFilesUploaded: "No files uploaded yet",
  publish: "Publish",
  yourBalance: "Your balance:",
  withdrawFunds: "Withdraw funds",
  depositFunds: "Deposit funds",
  useYourBalance:
    "Use your balance to buy access to premium Afroboost content and earn from sales.",
  withdrawFundsText:
    "Request a withdrawal to your PayPal account by entering an e-mail address associated with your PayPal account. Standard PayPal transaction fees may apply. Transactions will be processed in the next 7 to 14 working days.",
  yourEmailAddress: "Your e-mail address",
  carefulText: "Careful! Make sure you've entered the correct e-mail.",
  requestWithdraw: "Request a withdraw",
  depositFundsText:
    "Deposit funds to your account. Transaction fees will be calculated. Minimum amount is CHF 5.",
  totalPriceAfter:
    "Total price after calculating the transaction fees will be:",
  voucherCode: "Voucher code",
  messages: "Messages",
  enterMessage: "Enter your message here",
  voucherMessage:
    "Redeem funds from your gift card voucher by entering the voucher code below.",
  enterVoucher: "Enter your voucher code",
  activateVoucher: "Activate voucher",
  voucherGenerator: "Voucher generator",
  voucherGeneratorText:
    "As an administrator, you can generate voucher codes for your customers. Just input the value for the code in CHF, press the link below and the code will be instantly generated.",
  enterAmount: "Enter amount for the voucher",
  generateANewCode: "Generate a new code",
  voucherCodeIs: "Voucher code is",
  liveMeeting: "Live meeting",
  joinTheMeeting: "Join the meeting now",
  deleteComment: "Delete",
  searchby: "Search by username",
  editComment: "Edit",
  postComment: "Post a new comment",
  preview: "Preview",
  paymentConfirmation: "Payment confirmation",
  paymentConfirmationText: "Are you sure that you want to pay?",
  yes: "Yes",
  liveStream: "Set event countdown",
  chooseDate:
    "Choose a date that will be displayed as a countdown for a scheduled event.",
  no: "No",
  userNotFound: "User not found",
  userNotFoundText: "User with specified username does not exist on Afroboost.",
  aboutus: "About",
  contact: "Contact",
  contactText:
    "Got any questions? Feel free to contact us and we'll answer you as soon as possible.",
  uploadLoginVideo: "Upload your new video for login page",
  uploadVideo: "Upload video",
  publishNow: "Publish now",
  editLoginPage: "Edit login page",
  editHomebanner: "Edit home banner",
  uploadNewBanner: "Upload your new banner for homepage",
  uploadBanner: "Upload new banner",
  setNewBanner: "Set new banner",
  editAbout: "Edit about page",
  copyLinkText:
    "Copy the link of the post you want to be on the about page and paste it here:",
  changeNow: "Change now",
  generalConditions: "General conditions",
  uploadGeneralConditions: "Upload new file for general conditions",
  uploadFile: "Upload file",
  newFile: "Set new file",
  currentConditions: "See current general conditions file",
  adminPage: "Admin Page",
  editIntroVideo: "Edit intro video",
  manageUsers: "Manage Users",
  editBanner: "Edit banner",
  typeofUploadText: "Choose the type of content you want to upload",
  extensionError:
    "The file format is not supported. You can upload either png, jpg or jpeg for images and mp4, flv or avi for videos and mp3 for audio. Try uploading again.",
  extensionProductError:
    "The file format is not supported. You can upload either png, jpg or jpeg for images and mp4, flv or avi for videos. Try uploading again.",
  nameMonthlySub: "Name your monthly subscription",
  monthlyPrice: "Monthly price in CHF",
  nameQuartSub: "Name your quarterly subscription",
  quartPrice: "Quarterly price in CHF",
  nameAnnualSub: "Name your annual subscription",
  annualPrice: "Annual price in CHF",
  choosePostSubject: "Choose post subject",
  uploadProduct: "Upload your product",
  productTitle: "Product title",
  productDesc: "Product description",
  productPrice: "Product price",
  insufficientFunds: "Insufficient funds",
  pleaseDeposit:
    "Please deposit money to your account by visiting the 'Transfer' page or try again later.",
  depostiNow: "Deposit now",
  deletePost: "Delete post",
  deletePostMessage: "Are you sure that you want to delete this post?",
  editPost: "Edit post",
  productLabel: "Label of the product",
  oneProductPrice: "The price for one product is CHF ",
  quantity: "Quantity",
  size: "Size",
  fitnessSub: "Online Fitness Subscription",
  fitnessSubText: "Subscribe to get more fitness content.",
  periodTime: "Period of time",
  monthlySub: "Monthly Subscription",
  quartSub: "Quarterly Subscription",
  annualSub: "Annual Subscription",
  unsupportedFormat: "Unsupported format.",
  reply: "Reply to this comment",
  nothingBought: "You haven't bought anyhting yet! Start buying now!",
  payments: "Payments",
  subType: "Subsrciption type",
  productType: "Product type",
  dateBought: "Date bought",
  boughtFrom: "Bought from",
  soldPosts: "Sold posts",
  noSoldPosts:
    "Nobody has bought anything yet! Start posting your products now!",
  boughtBy: "Bought by",
  emailVoucher: "E-mail of the voucher receiver",
  transactions: "Transactions",
  youGetPercent:
    "You get 95% of the price from posts that are bought from you.",
  uploadYourFiles: "Upload your files here:",
  websiteUnderConstruction: "The website is under construction",
};

export default English;
