const France = {
  homepage: "Accueil",
  searchAfroboost: "Rechercher",
  "Latest posts": "Derniers articles",
  Everything: "Tout",
  Entertainment: "Divertissement",
  Sport: "Sport",
  Music: "Musique",
  Film: "Film",
  Services: "Services",
  Podcasts: "Podcasts",
  Animations: "Animations",
  profile: "Profil",
  Tutorials: "Tutoriels",
  Vouchers: "Pièces justificatives",
  searchAuthor: "Rechercher l'auteur sur Afroboost",
  library: "Galerie",
  liked: "Favoris",
  autoplay: "Autoplay",
  transfer: "Transfert",
  logout: "Se déconnecter",
  posts: "Des postes",
  searchPostsAuthor: "Rechercher les articles de l'auteur",
  "Oldest posts": "Anciens articles",

  liveStream: "Définir le compte à rebours de l'événement",
  chooseDate:
    "Choisissez une date qui sera affichée comme compte à rebours pour un événement programmé.",
  posted: "Publié",
  changeYourUsername: "Changez votre nom d'utilisateur",
  changeYourUsernameText:
    "Votre nom doit être composé uniquement de caractères alphanumériques et ne peut contenir aucun autre caractère.",
  yourNewUsername: "Your new username",
  cancel: "Annuler",
  confirm: "Confirmer",
  changeYourBiography: "Changez votre biographie",
  changeYourBiographyText:
    "Votre biographie sera visible publiquement sur votre page de profil.",
  yourNewBiography: "Votre nouvelle biographie",
  changeYourName: "Changez votre nom",
  changeYourNameText:
    "Votre nom ne doit être composé que de caractères alphabétiques et ne peut contenir aucun autre caractère.",
  yourNewName: "Votre nouveau nom",
  publishPost: "Publier un nouveau message",
  publishPostFirst:
    "Partagez votre contenu sur Afroboost et gagnez de l'argent grâce aux ventes. Les vidéos et fichiers audio payants auront une version de prévisualisation non payante.",
  titlePost: "Titre de votre message",
  descriptionPost: "Description de votre message",
  pricePost: "Prix de votre courrier en CHF",
  upload: "TÉLÉCHARGER",
  category: "Catégorie",
  noFilesUploaded: "Aucun fichier téléversé pour le moment",
  searchby: "Recherche par nom d'utilisateur",
  publish: "Publier",
  yourBalance: "Your balance:",
  withdrawFunds: "Retirer des fonds",
  depositFunds: "Fonds de dépôt",
  useYourBalance:
    "Utilisez votre solde pour acheter un accès au contenu Afroboost premium et gagner des ventes.",
  withdrawFundsText:
    "Demandez un retrait sur votre compte PayPal en saisissant une adresse e-mail associée à votre compte PayPal. Des frais de transaction PayPal standard peuvent s'appliquer. Les transactions seront traitées dans les 7 à 14 prochains jours ouvrables.",
  yourEmailAddress: "Your e-mail address",
  carefulText:
    "Attention! Assurez-vous d'avoir saisi l'adresse e-mail correcte.",
  requestWithdraw: "Demander un retrait",
  depositFundsText:
    "Déposez des fonds sur votre compte. Les frais de transaction seront calculés. Le montant minimum est de CHF 5.",
  totalPriceAfter:
    "Le prix total après le calcul des frais de transaction sera:",
  voucherCode: "Code du bon",
  message: "Message",
  messages: "Messages",
  enterMessage: "Entrez votre message ici",
  voucherMessage:
    "Utilisez les fonds de votre bon de carte-cadeau en saisissant le code de bon ci-dessous.",
  enterVoucher: "Enter your voucher code",
  activateVoucher: "Activer le bon",
  voucherGenerator: "Voucher generator",
  voucherGeneratorText:
    "En tant qu'administrateur, vous pouvez générer des codes de réduction pour vos clients. Entrez simplement la valeur du code en CHF, appuyez sur le lien ci-dessous et le code sera instantanément généré.",
  enterAmount: "Entrez le montant du bon",
  generateANewCode: "Générer un nouveau code",
  voucherCodeIs: "Le code du bon est",
  liveMeeting: "Live meeting",
  joinTheMeeting: "Rejoignez la réunion maintenant",
  deleteComment: "Effacer",
  editComment: "Éditer",
  postComment: "Publier un nouveau commentaire",
  preview: "Aperçu",
  paymentConfirmation: "Confirmation de paiement",
  paymentConfirmationText: "Etes-vous sûr de vouloir payer?",
  yes: "Oui",
  no: "Non",
  userNotFound: "Utilisateur non trouvé",
  userNotFoundText:
    "L'utilisateur avec le nom d'utilisateur spécifié n'existe pas sur Afroboost.",

  "No biography provided": "Aucune biographie",
  Member: "Abonné",

  aboutus: "À propos",
  contact: "Contacter",
  contactText:
    "Vous avez des questions? N'hésitez pas à nous contacter et nous vous répondrons dans les plus brefs délais.",
  uploadLoginVideo:
    "Téléchargez votre nouvelle vidéo pour la page de connexion",
  uploadVideo: "Télécharger une video",
  publishNow: "Publier maintenant",
  editLoginPage: "Modifier la page de connexion",
  editHomeBanner: "Modifier la bannière d'accueil",
  uploadNewBanner: "Téléchargez votre nouvelle bannière pour la page d'accueil",
  uploadBanner: "Télécharger une nouvelle bannière",
  setNewBanner: "Définir une nouvelle bannière",
  editAbout: "À propos de la page",
  copyLinkText:
    "Copiez le lien du message que vous souhaitez afficher sur la page À propos et collez-le ici:",
  changeNow: "Change maintenant",
  generalConditions: "Conditions générales",
  uploadGeneralConditions:
    "Télécharger un nouveau fichier pour les conditions générales",
  uploadFile: "Téléverser un fichier",
  newFile: "Définir un nouveau fichier",
  currentConditions: "Voir le fichier des conditions générales en vigueur",
  adminPage: "Page d'administration",
  editIntroVideo: "Vidéo d'introduction",
  manageUsers: "Gérer les utilisateurs",
  editBanner: "Bannière",
  typeofUploadText:
    "Choisissez le type de contenu que vous souhaitez télécharger",
  extensionError:
    "Le format de fichier n'est pas pris en charge. Vous pouvez télécharger des fichiers png, jpg ou jpeg pour les images et mp4, flv ou avi pour les vidéos et mp3 pour l'audio. Essayez à nouveau de téléverser.",
  extensionProductError:
    "Le format de fichier n'est pas pris en charge. Vous pouvez télécharger des fichiers png, jpg ou jpeg pour les images et mp4, flv ou avi pour les vidéos. Veuillez réessayer.",
  nameMonthlySub: "Nommez votre abonnement mensuel",
  monthlyPrice: "Prix mensuel en CHF",
  nameQuartSub: "Nommez votre abonnement trimestriel",
  quartPrice: "Prix trimestriel en CHF",
  nameAnnualSub: "Nommez votre abonnement annuel",
  annualPrice: "Prix annuel en CHF",
  choosePostSubject: "Choisissez le sujet du message",
  uploadProduct: "Téléchargez votre produit",
  productTitle: "Titre du produit",
  productDesc: "Description du produit",
  productPrice: "Prix du produit",
  insufficientFunds: "Fonds insuffisants",
  pleaseDeposit:
    "Veuillez déposer de l'argent sur votre compte en visitant la page 'Transférer' ou réessayer plus tard.",
  depostiNow: "Déposez maintenant",
  deletePost: "Supprimer le message",
  deletePostMessage: "Êtes-vous sûr de vouloir supprimer ce message?",
  editPost: "Modifier le message",
  productLabel: "Etiquette du produit",
  oneProductPrice: "Le prix pour un produit est de CHF",
  quantity: "Quantité",
  size: "Taille",
  fitnessSub: "Abonnement Fitness en ligne",
  fitnessSubText:
    "Abonnez-vous pour obtenir plus de contenu de remise en forme.",
  periodTime: "Période de temps",
  monthlySub: "Souscription mensuelle",
  quartSub: "Abonnement trimestriel",
  annualSub: "Souscription annuelle",
  unsupportedFormat: "Format non supporté.",
  reply: "Répondre à ce commentaire",
  nothingBought:
    "Vous n'avez encore rien acheté! Commencez à acheter maintenant!",
  payments: "Paiements",
  subType: "Type d'abonnement",
  productType: "Type de produit",
  dateBought: "Date d'achat",
  boughtFrom: "Acheté à",
  soldPosts: "Articles vendus",
  noSoldPosts:
    "Personne n'a encore rien acheté! Commencez à publier vos produits dès maintenant!",
  boughtBy: "Acheté par",
  emailVoucher: "E-mail du destinataire du bon",
  transactions: "Transactions",
  youGetPercent:
    "Vous obtenez 95% du prix des publications qui vous sont achetées.",
  uploadYourFiles: "Téléchargez vos fichiers ici:",
  websiteUnderConstruction: "Le site est en construction",
};

export default France;
