const Germany = {
  homepage: "Startseite",
  searchAfroboost: "Suche Afroboost",
  "Latest posts": "Neueste Beiträge",
  Everything: "Alles",
  Entertainment: "Unterhaltung",
  Sport: "Sport",
  Music: "Musik",
  profile: "Profile",
  Film: "Film",
  Services: "Dienstleistungen",
  Podcasts: "Podcasts",
  Animations: "Animationen",
  Tutorials: "Tutorials",
  Vouchers: "Gutscheine",
  searchAuthor: "Autor auf Afroboost suchen",
  library: "Bibliothek",
  liked: "Gefallen",
  transfer: "Transfer",
  logout: "Ausloggen",
  posts: "Beiträge",
  searchPostsAuthor: "Suche nach Autorenbeiträgen",
  "Oldest posts": "Älteste Beiträge",
  posted: "Gesendet",
  searchby: "Suche nach Benutzername",
  changeYourUsername: "Ändern Sie Ihren Benutzernamen",
  changeYourUsernameText:
    "Ihr Name sollte nur aus alphanumerischen Zeichen bestehen und darf keine anderen Zeichen enthalten.",
  yourNewUsername: "Ihr neuer Benutzername",
  cancel: "Stornieren",
  confirm: "Bestätigen",
  changeYourBiography: "Ändere deine Biographie",
  changeYourBiographyText:
    "Ihre Biografie wird auf Ihrer Profilseite öffentlich sichtbar sein.",
  yourNewBiography: "Deine neue Biographie",
  changeYourName: "Ändere deinen Namen",
  changeYourNameText:
    "Your name should consist only of alphabetic characters and cannot contain any other characters.",
  yourNewName: "Dein neuer Name",
  publishPost: "Neuen Beitrag veröffentlichen",
  publishPostFirst:
    "Teilen Sie Ihre Inhalte auf Afroboost und verdienen Sie Geld mit Verkäufen. Bezahlte Videos und Audiodateien haben eine nicht bezahlte Vorschau-Version.",
  titlePost: "Titel für Ihren Beitrag",
  descriptionPost: "Beschreibung für Ihren Beitrag",
  pricePost: "Preis für Ihren Beitrag in CHF",
  upload: "HOCHLADEN",
  category: "Kategorie",
  noFilesUploaded: "Noch keine Dateien hochgeladen",
  publish: "Veröffentlichen",
  yourBalance: "Ihr Geldguthaben:",
  withdrawFunds: "Auszahlungen",
  depositFunds: "Einlagen",
  useYourBalance:
    "Verwenden Sie Ihr Guthaben, um Zugang zu Premium-Afroboost-Inhalten zu erhalten und mit Verkäufen zu verdienen.",
  withdrawFundsText:
    "Fordern Sie eine Auszahlung auf Ihr PayPal-Konto an, indem Sie eine E-Mail-Adresse eingeben, die Ihrem PayPal-Konto zugeordnet ist. Es können Standard-PayPal-Transaktionsgebühren anfallen. Transaktionen werden in den nächsten 7 bis 14 Werktagen verarbeitet.",
  yourEmailAddress: "Deine Emailadresse",
  carefulText:
    "Vorsicht! Stellen Sie sicher, dass Sie die richtige E-Mail-Adresse eingegeben haben.",
  requestWithdraw: "Rücktritt beantragen",
  depositFundsText:
    "Zahlen Sie Geld auf Ihr Konto ein. Transaktionsgebühren werden berechnet. Der Mindestbetrag beträgt CHF 5.",
  totalPriceAfter:
    "Der Gesamtpreis nach Berechnung der Transaktionsgebühren beträgt:",
  voucherCode: "Coupon Code",
  autoplay: "Automatisches Abspielen",
  message: "Mitteilung",
  messages: "Mitteilungen",
  enterMessage: "Geben Sie hier Ihre Nachricht ein",
  voucherMessage:
    "Lösen Sie Geld von Ihrem Geschenkgutschein ein, indem Sie den folgenden Gutscheincode eingeben.",
  enterVoucher: "Geben Sie Ihren Gutscheincode ein",
  activateVoucher: "Gutschein aktivieren",
  voucherGenerator: "Gutscheingenerator",
  voucherGeneratorText:
    "Als Administrator können Sie Gutscheincodes für Ihre Kunden generieren. Geben Sie einfach den Wert für den Code in CHF ein, klicken Sie auf den folgenden Link, und der Code wird sofort generiert.",
  enterAmount: "Betrag für den Gutschein eingeben",
  generateANewCode: "Neuen Code generieren",
  voucherCodeIs: "Gutscheincode ist",
  liveMeeting: "Live-Meeting",
  joinTheMeeting: "Nehmen Sie jetzt an der Besprechung teil",
  deleteComment: "Löschen",
  editComment: "Bearbeiten",
  postComment: "Neuen Kommentar posten",
  preview: "Vorschau",
  paymentConfirmation: "Zahlungsbestätigung",
  paymentConfirmationText: "Sind Sie sicher, dass Sie bezahlen möchten?",
  yes: "Ja",
  no: "Nein",
  userNotFound: "Benutzer wurde nicht gefunden",
  userNotFoundText:
    "Benutzer mit angegebenem Benutzernamen existiert auf Afroboost nicht.",
  aboutus: "Über",
  contact: "Kontakt",
  contactText:
    "Haben Sie Fragen? Nehmen Sie Kontakt mit uns auf und wir werden Ihnen so schnell wie möglich antworten.",
  uploadLoginVideo: "Laden Sie Ihr neues Video für die Anmeldeseite hoch",
  uploadVideo: "Video hochladen",
  publishNow: "Jetzt veröffentlichen",
  editLoginPage: "Anmeldeseite bearbeiten",
  editHomebanner: "Banner bearbeiten",
  uploadNewBanner: "Laden Sie Ihr neues Banner für die Homepage hoch",
  uploadBanner: "Laden Sie ein neues Banner hoch",
  setNewBanner: "Setze neues Banner",
  editAbout: "Über Seite bearbeiten",
  copyLinkText:
    "Kopieren Sie den Link des Beitrags, den Sie auf der About-Seite haben möchten, und fügen Sie ihn hier ein:",
  changeNow: "Jetzt ändern",
  generalConditions: "Allgemeine Bedingungen",
  uploadGeneralConditions:
    "Laden Sie eine neue Datei für allgemeine Bedingungen hoch",
  uploadFile: "Datei hochladen",
  newFile: "Neue Datei einstellen",
  currentConditions: "Siehe aktuelle Datei mit den allgemeinen Bedingungen",
  adminPage: "Administrator Seite",
  editIntroVideo: "Intro-Video bearbeiten",
  manageUsers: "Benutzer verwalten",
  editBanner: "Banner bearbeiten",
  typeofUploadText: "Wählen Sie den Inhaltstyp aus, den Sie hochladen möchten",
  extensionError:
    "Das Dateiformat wird nicht unterstützt. Sie können entweder PNG, JPG oder JPEG für Bilder und MP4, FLV oder AVI für Videos und MP3 für Audio hochladen. Versuchen Sie es erneut.",
  extensionProductError:
    "Das Dateiformat wird nicht unterstützt. Sie können entweder png, jpg oder jpeg für Bilder und mp4, flv oder avi für Videos hochladen. Versuchen Sie es erneut.",
  nameMonthlySub: "Nennen Sie Ihr monatliches Abonnement",
  monthlyPrice: "Monatspreis in CHF",
  nameQuartSub: "Nennen Sie Ihr vierteljährliches Abonnement",
  quartPrice: "Vierteljährlicher Preis in CHF",
  nameAnnualSub: "Nennen Sie Ihr Jahresabonnement",
  annualPrice: "Jahrespreis in CHF",
  choosePostSubject: "Wählen Sie den Betreff des Beitrags",
  uploadProduct: "Laden Sie Ihr Produkt hoch",
  productTitle: "Produktname",
  productDesc: "Produktbeschreibung",
  productPrice: "Produktpreis",
  insufficientFunds: "Unzureichende Mittel",
  pleaseDeposit:
    "Bitte zahlen Sie Geld auf Ihr Konto ein, indem Sie die Seite 'Überweisung' besuchen, oder versuchen Sie es später erneut.",
  depostiNow: "Jetzt einzahlen",
  deletePost: "Beitrag entfernen",
  deletePostMessage:
    "Sind Sie sicher, dass Sie diesen Beitrag löschen möchten?",
  editPost: "Beitrag bearbeiten",
  productLabel: "Etikett des Produkts",
  oneProductPrice: "Der Preis für ein Produkt beträgt CHF ",
  quantity: "Menge",
  size: "Größe",
  fitnessSub: "Online Fitness Abonnement",
  fitnessSubText: "Abonnieren Sie, um mehr Fitnessinhalte zu erhalten.",
  periodTime: "Zeitspanne",
  monthlySub: "Monatliches Abo",
  quartSub: "Vierteljährliches Abonnement",
  annualSub: "Jahresabonnement",
  unsupportedFormat: "Nicht unterstütztes Format.",
  reply: "Auf diesen Kommentar antworten",
  nothingBought: "Du hast noch nichts gekauft! Kaufen Sie jetzt!",
  payments: "Zahlungen",
  subType: "Abonnementtyp",
  productType: "Produktart",
  dateBought: "Kaufdatum",
  boughtFrom: "Gekauft von",
  soldPosts: "Verkaufte Beiträge",
  noSoldPosts:
    "Noch hat niemand etwas gekauft! Veröffentlichen Sie jetzt Ihre Produkte!",
  boughtBy: "Gekauft von",
  emailVoucher: "E-Mail des Gutscheinempfängers",
  transactions: "Transaktionen",
  youGetPercent:
    "Sie erhalten 95% des Preises von Posts, die Sie gekauft haben.",
  uploadYourFiles: "Laden Sie Ihre Dateien hier hoch:",
  websiteUnderConstruction: "Die Website befindet sich im Aufbau",
};

export default Germany;
