const Spain = {
  homepage: "Homepage",
  searchAfroboost: "Buscar Afroboost",
  "Latest posts": "La mas nueva",
  Everything: "Todo",
  Entertainment: "Entretenimiento",
  Sport: "Deporte",
  Music: "Música",
  Film: "Película",
  Services: "Servicios",
  Podcasts: "Podcasts",
  Animations: "Animaciones",
  Tutorials: "Tutoriales",
  Vouchers: "Vales",
  searchAuthor: "Buscar autor en Afroboost",
  library: "Biblioteca",
  liked: "Apreciado",
  transfer: "Transferir",
  logout: "Cerrar sesión",
  posts: "Publicaciones",
  profile: "Profile",
  searchPostsAuthor: "Buscar publicaciones del autor",
  "Oldest posts": "Antiguas",
  posted: "Al corriente",
  searchby: "Buscar por nombre de usuario",
  changeYourUsername: "Cambia tu nombre de usuario",
  changeYourUsernameText:
    "Su nombre debe constar solo de caracteres alfanuméricos y no puede contener ningún otro carácter.",
  yourNewUsername: "Tu nuevo nombre de usuario",
  cancel: "Cancelar",
  confirm: "Confirmar",
  changeYourBiography: "Cambia tu biografía",
  changeYourBiographyText:
    "Tu biografía será visible públicamente en tu página de perfil",
  yourNewBiography: "Tu nueva biografía",
  changeYourName: "Cambia tu nombre",
  changeYourNameText:
    "Su nombre debe constar únicamente de caracteres alfabéticos y no puede contener ningún otro carácter",
  yourNewName: "Tu nuevo nombre",
  publishPost: "Publicar una nueva publicación",
  publishPostFirst:
    "Comparta su contenido en Afroboost y gane dinero con las ventas. Los videos y archivos de audio pagos tendrán una versión de vista previa gratuita",
  titlePost: "Título de tu publicación",
  descriptionPost: "Descripción de tu publicación",
  pricePost: "Precio de tu publicación en CHF",
  upload: "SUBIR",
  category: "Categoría",
  noFilesUploaded: "Aún no se han subido archivos",
  publish: "Publish",
  yourBalance: "Tu saldo de dinero:",
  withdrawFunds: "Retirar Fondos",
  depositFunds: "Fondos de depósito",
  useYourBalance:
    "Use su saldo para comprar acceso a contenido premium de Afroboost y ganar dinero con las ventas",
  withdrawFundsText:
    "Solicite un retiro a su cuenta PayPal ingresando una dirección de correo electrónico asociada con su cuenta PayPal. Se pueden aplicar tarifas de transacción estándar de PayPal. Las transacciones se procesarán en los próximos 7 a 14 días hábiles.",
  yourEmailAddress: "Tu correo electrónico",
  carefulText:
    "¡Cuidado! Asegúrate de haber ingresado el correo electrónico correcto.",
  requestWithdraw: "Solicitar un retiro",
  depositFundsText:
    "Deposite fondos en su cuenta. Se calcularán las tarifas de transacción. La cantidad mínima es 5 CHF",
  totalPriceAfter:
    "El precio total después de calcular las tarifas de transacción será:",
  voucherCode: "Código de cupón",
  message: "Mensaje",
  messages: "Mensajes",
  autoplay: "Autoplay",
  enterMessage: "Introduzca su mensaje aquí",
  voucherMessage:
    "Canjee fondos de su cupón de tarjeta de regalo ingresando el código de cupón a continuación.",
  enterVoucher: "Ingrese su código de cupón",
  activateVoucher: "Activar cupón",
  voucherGenerator: "Generador de vales",
  voucherGeneratorText:
    "Como administrador, puede generar códigos de cupón para sus clientes. Simplemente ingrese el valor del código en CHF, presione el enlace a continuación y el código se generará instantáneamente.",
  enterAmount: "Ingrese el monto del bono",
  generateANewCode: "Generar un código nuevo",
  voucherCodeIs: "El código del cupón es",
  liveMeeting: "Reunión en vivo",
  joinTheMeeting: "Únase a la reunión ahora",
  deleteComment: "Borrar",
  editComment: "Editar",
  postComment: "Publica un comentario nuevo",
  preview: "Avance",
  paymentConfirmation: "Confirmación de pago",
  paymentConfirmationText: "¿Estás seguro de que quieres pagar?",
  yes: "Sí",
  no: "No",
  userNotFound: "Usuario no encontrado",
  userNotFoundText:
    "El usuario con el nombre de usuario especificado no existe en Afroboost",
  aboutus: "Acerca de",
  contact: "Contacto",
  contactText:
    "¿Tienes preguntas? Contacta con nosotros y te responderemos lo antes posible.",
  uploadLoginVideo: "Sube tu nuevo video para la página de inicio de sesión",
  uploadVideo: "Subir video",
  publishNow: "Publica ahora",
  editLoginPage: "Editar inicio de sesión",
  editHomebanner: "Editar banner",
  uploadNewBanner: "Sube tu nuevo banner para la página de inicio",
  uploadBanner: "Subir un nuevo banner",
  setNewBanner: "Establecer nuevo banner",
  editAbout: "Acerca de editar",
  copyLinkText:
    "Copie el enlace de la publicación que desea en la página Acerca de y péguelo aquí:",
  changeNow: "Cambia ahora",
  generalConditions: "Términos y condiciones",
  uploadGeneralConditions:
    "Cargue un nuevo archivo para conocer los términos y condiciones generales",
  uploadFile: "Subir archivo",
  newFile: "Establecer un nuevo archivo",
  currentConditions: "Ver el archivo actual con las condiciones generales",
  adminPage: "Página de administrador",
  editIntroVideo: "Editar video de introducción",
  manageUsers: "Administrar usuarios",
  editBanner: "Editar banner",
  typeofUploadText: "Seleccione el tipo de contenido que desea cargar",
  extensionError:
    "El formato de archivo no es compatible. Puede cargar PNG, JPG o JPEG para imágenes y MP4, FLV o AVI para videos y MP3 para audio. Pruébalo otra vez.",
  extensionProductError:
    "El formato de archivo no es compatible. Puede cargar png, jpg o jpeg para imágenes y mp4, flv o avi para videos. Intente cargar nuevamente.",
  nameMonthlySub: "Nombra tu suscripción mensual",
  monthlyPrice: "Precio mensual en CHF",
  nameQuartSub: "Nombra tu suscripción trimestral",
  quartPrice: "Precio trimestral en CHF",
  nameAnnualSub: "Nombra tu suscripción anual",
  annualPrice: "Precio anual en CHF",
  choosePostSubject: "Elija el tema de la publicación",
  uploadProduct: "Sube tu producto",
  productTitle: "Titulo del producto",
  productDesc: "Descripción del Producto",
  productPrice: "Precio del producto",
  insufficientFunds: "Fondos insuficientes",
  pleaseDeposit:
    "Deposite dinero en su cuenta visitando la página 'Transferir' o inténtelo de nuevo más tarde.",
  depostiNow: "Depositar ahora",
  deletePost: "Eliminar mensaje",
  deletePostMessage: "¿Estás seguro de que deseas eliminar esta publicación?",
  editPost: "Editar post",
  productLabel: "Etiqueta del producto",
  oneProductPrice: "El precio de un producto es CHF",
  quantity: "Cantidad",
  size: "Tamaño",
  fitnessSub: "Suscripción de fitness online",
  fitnessSubText: "Suscríbete para obtener más contenido de fitness.",
  periodTime: "Período de tiempo",
  monthlySub: "Suscripción mensual",
  quartSub: "Suscripción trimestral",
  annualSub: "Suscripción anual",
  unsupportedFormat: "Formato no compatible.",
  reply: "Responder a este comentario",
  nothingBought: "¡Aún no has comprado nada! ¡Empiece a comprar ahora!",
  payments: "Payments",
  subType: "Tipo de suscripción",
  productType: "Tipo de producto",
  dateBought: "Fecha de compra",
  boughtFrom: "Comprado en",
  soldPosts: "Publicaciones vendidas",
  noSoldPosts:
    "¡Nadie ha comprado nada todavía! ¡Empiece a publicar sus productos ahora!",
  boughtBy: "Comprado por",
  emailVoucher: "Correo electrónico del destinatario del cupón",
  transactions: "Actas",
  youGetPercent:
    "Obtienes el 95% del precio de las publicaciones que te compran.",
  uploadYourFiles: "Sube tus archivos aquí:",
  websiteUnderConstruction: "El sitio web está en construcción",
};

export default Spain;
